schema = 3
cachePackages = [
  'charm.land/bubbles/v2/cursor',
  'charm.land/bubbles/v2/filepicker',
  'charm.land/bubbles/v2/help',
  'charm.land/bubbles/v2/key',
  'charm.land/bubbles/v2/spinner',
  'charm.land/bubbles/v2/textarea',
  'charm.land/bubbles/v2/textinput',
  'charm.land/bubbles/v2/viewport',
  'charm.land/bubbletea/v2',
  'charm.land/huh/v2',
  'charm.land/lipgloss/v2',
  'charm.land/log/v2',
  'github.com/Deskilling/gopkg/pkg/config',
  'github.com/Deskilling/gopkg/pkg/filesystem',
  'github.com/Deskilling/gopkg/pkg/m3u8',
  'github.com/PuerkitoBio/goquery',
  'github.com/andybalholm/cascadia',
  'github.com/atotto/clipboard',
  'github.com/catppuccin/go',
  'github.com/charmbracelet/colorprofile',
  'github.com/charmbracelet/ultraviolet',
  'github.com/charmbracelet/x/ansi',
  'github.com/charmbracelet/x/ansi/kitty',
  'github.com/charmbracelet/x/ansi/parser',
  'github.com/charmbracelet/x/exp/ordered',
  'github.com/charmbracelet/x/exp/strings',
  'github.com/charmbracelet/x/term',
  'github.com/charmbracelet/x/termios',
  'github.com/charmbracelet/x/windows',
  'github.com/clipperhouse/displaywidth',
  'github.com/clipperhouse/uax29/v2/graphemes',
  'github.com/dustin/go-humanize',
  'github.com/go-logfmt/logfmt',
  'github.com/lucasb-eyer/go-colorful',
  'github.com/mattn/go-runewidth',
  'github.com/mitchellh/hashstructure/v2',
  'github.com/muesli/cancelreader',
  'github.com/pelletier/go-toml/v2',
  'github.com/pelletier/go-toml/v2/unstable',
  'github.com/rivo/uniseg',
  'github.com/xo/terminfo',
  'golang.org/x/exp/slices',
  'golang.org/x/net/html',
  'golang.org/x/net/html/atom',
  'golang.org/x/sync/errgroup',
  'golang.org/x/sys/unix',
  'golang.org/x/text/transform',
  'golang.org/x/text/unicode/norm'
]

[mod]
  [mod.'charm.land/bubbles/v2']
    version = 'v2.0.0'
    hash = 'sha256-MhBifn4m+BTZrO8twl9jutDFWMVzWvfYLsJfQc2zeg4='

  [mod.'charm.land/bubbletea/v2']
    version = 'v2.0.2'
    hash = 'sha256-oWZTg8c3uM0oJfibwIGvh0PbBj6ikoxuk+/cZ4Jm924='

  [mod.'charm.land/huh/v2']
    version = 'v2.0.3'
    hash = 'sha256-8YAdd4qbfsMiPFI+xRxYmiDykqIHkih+7IPZ6PWB4EI='

  [mod.'charm.land/lipgloss/v2']
    version = 'v2.0.2'
    hash = 'sha256-b9t+NjParxoubrUwHUqiFUrebsq4H7NDUptJ3Jmx+m0='

  [mod.'charm.land/log/v2']
    version = 'v2.0.0'
    hash = 'sha256-UpdpM11MkNx20lXC46vtMp7PZ0H0GXvX7ZN9STo5qHE='

  [mod.'github.com/Deskilling/gopkg']
    version = 'v0.0.0-20260425145211-86cbbd8c946b'
    hash = 'sha256-23WXulaoeTOD32SkFgO0cGcgoQqE8KgPb58HdFa9F4g='

  [mod.'github.com/PuerkitoBio/goquery']
    version = 'v1.11.0'
    hash = 'sha256-Au/xzPOirIaMb9ElkMsJtOzqXBhqM5+4K0EQIo4oaPA='

  [mod.'github.com/andybalholm/cascadia']
    version = 'v1.3.3'
    hash = 'sha256-jv7ZshpSd7FZzKKN6hqlUgiR8C3y85zNIS/hq7g76Ho='

  [mod.'github.com/atotto/clipboard']
    version = 'v0.1.4'
    hash = 'sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk='

  [mod.'github.com/catppuccin/go']
    version = 'v0.2.0'
    hash = 'sha256-/MZXZD/WlVh75ruSOnq+HlMVNz9vMfpaTIXT//CZU4k='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.2'
    hash = 'sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20260205113103-524a6607adb8'
    hash = 'sha256-zHe+nAS80nJPgZ4c3mU2HcHA9QL486b0BiyC4FNK3Nk='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.6'
    hash = 'sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI='

  [mod.'github.com/charmbracelet/x/exp/ordered']
    version = 'v0.1.0'
    hash = 'sha256-e+71nPaTOvtRGz5TkhMKWNpyj3IRjuAkSluLpSclBgA='

  [mod.'github.com/charmbracelet/x/exp/strings']
    version = 'v0.0.0-20240722160745-212f7b056ed0'
    hash = 'sha256-NWe8LHXUtrrABWFhmAzLNYAZyJIwN3C/T2OdaInjl9E='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.11.0'
    hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.0'
    hash = 'sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.21'
    hash = 'sha256-JU+ZijAu0o+5jzfLC8ytQzxIAKYr5ow3nCjFf0ehpiA='

  [mod.'github.com/mitchellh/hashstructure/v2']
    version = 'v2.0.2'
    hash = 'sha256-O4Yw4pPQECWe8DoVDIH2nUMN8Zl8waS7/O1sv18M2Xs='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.0'
    hash = 'sha256-3ftKBqSwUp5rs10NigReAJ8RxfnP4Aol45EkP0XRaa4='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20250106191152-7588d65b2ba8'
    hash = 'sha256-caQtMKFNsyOLf7nvgMo7jza9Os5mP24DiPQg3/BRGVA='

  [mod.'golang.org/x/net']
    version = 'v0.48.0'
    hash = 'sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.42.0'
    hash = 'sha256-LhNedvUEJbPYyR6EoU91rfOr3DBBoauLOcMcyqghEos='

  [mod.'golang.org/x/text']
    version = 'v0.32.0'
    hash = 'sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs='
